
user_input1 = input("Whats your Fav Animal")
print(user_input1 + "Dope ")
user_input2 = input("What noise do thay make:")
print(user_input2 + "Thats Cool ")
user_input3 = input("Why do you like them:")
print(user_input3 + "Thats Sick ")
user_input4 = input("Where do thay live:")
print(user_input4 + "Thats cool ")
user_input5 = input("What do thay eat:")
print(user_input5 + "Thats sound good ")
user_input6 = input("Are thay house pets:")
print(user_input6 + "good to know ")

user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
user_input3 = input("What noise do thay make:")
print(user_input3 + "Thats good looking")
