user_input1 = input("Whats your Fav Animal")
print(user_input1 + " Dope ")
user_input2 = input("What noise do thay make:")
print(user_input2 + " Thats Cool")
user_input3 = input("Why do you like them:")
print(user_input3 + " Thats Sick ")
user_input4 = input("Where do thay live:")
print(user_input4 + " Thats cool ")
user_input5 = input("What do thay eat:")
print(user_input5 + " Thats sound good ")
user_input6 = input("Are thay house pets:")
print(user_input6 + " good to know ")
user_input7 = input("What size are thay:")
print(user_input7 + " Dang")
user_input8 = input("Where can you find them:")
print(user_input8 + " Ok good to know")
user_input9 = input("What noise do thay make:")
print(user_input9 + " Thats good looking")
user_input10 = input("Whats a fun fact about them:")
print(user_input10 + " thats a good fun fact")
print("so your favorite animal is " + user_input1 + " thay make a " + user_input2 + " noise " " you like them becaue " + user_input3 + " thay live in the " + user_input4 + " thay eat " + user_input5)
